In [25]:
#General
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

#Miscellaneous
#import random
import numpy as np
import sys

#Regression
    #General
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

    #Regressors
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR

#Evaluation
from sklearn.model_selection import cross_val_score
#from sklearn.metrics import mean_squared_error

#CODE vv
#Data importing
print("Task 1.1 | Data Preparation")
#skipfooter=523 if blank rows are an issue
inputData = pd.read_excel("ENB2012_data.xlsx", usecols="A,B,C,D,E,F,G,H")
targetData = pd.read_excel("ENB2012_data.xlsx", usecols="I,J")
SVRTargetData = pd.read_excel("ENB2012_data.xlsx", usecols="I")
#print(inputData)
#print(targetData)

#Conversion to array
targetDataArray = np.array(targetData)
SVRTargetDataArray = np.array(SVRTargetData)
SVRTargetDataTrueArray = np.ravel(SVRTargetDataArray)
#print(SVRTargetDataTrueArray)

#Normalisation
normaliser = MinMaxScaler()
normalisedInputData = normaliser.fit_transform(inputData)
#print(normalisedInputData)

#Input & target data
x_input, x_target, y_input, y_target = train_test_split(normalisedInputData, targetDataArray)
x_inputSVR, x_targetSVR, y_inputSVR, y_targetSVR = train_test_split(normalisedInputData, SVRTargetDataTrueArray)

#Random Forest Regressor v2
print("RANDOM FOREST REGRESSOR:")
RFRegressor = RandomForestRegressor()
RFRegressor.fit(x_input, y_input)
RFROutput = RFRegressor.predict(x_target)
print("Mean Absolute Error:")
meanAbsoluteErrorRFR = mean_absolute_error(y_target, RFROutput)
print(meanAbsoluteErrorRFR)
print("Cross-Validation:")
crossValidatedScore = cross_val_score(RFRegressor, x_input, y_input)
print(crossValidatedScore)
#trained regressor, test input, test target

#Random Forest Regressor
#print("RANDOM FOREST REGRESSOR - Old:")
#RFRegressor = RandomForestRegressor()
#RFRegressor.fit(normalisedInputData, targetDataArray)
#RFROutput = RFRegressor.predict(normalisedInputData)
#print("Mean Absolute Error:")
#meanAbsoluteErrorRFR = mean_absolute_error(targetDataArray, RFROutput)
#print(meanAbsoluteErrorRFR)
#print("Cross-Validation:")
#crossValidatedScore = cross_val_score(meanAbsoluteErrorRFR, normalisedInputData, targetDataArray)
#print(crossValidatedScore)

#RFRegressor = RandomForestRegressor(max_depth=2, random_state=0)

#MLPRegressor
print("MLPREGRESSOR:")
regressor = MLPRegressor(max_iter=100000)
regressor.fit(x_input, y_input)
MLPOutput = regressor.predict(x_target)
print("Mean Absolute Error:")
print(mean_absolute_error(y_target, MLPOutput))
print("Cross-Validation:")
crossValidatedScore = cross_val_score(regressor, x_input, y_input)
print(crossValidatedScore)

#SVR Regressor
print("SVR REGRESSOR:")
SVRRegressor = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.2))
SVRRegressor.fit(x_inputSVR, y_inputSVR)
SVROutput = SVRRegressor.predict(x_targetSVR)
print("Mean Absolute Error:")
print(mean_absolute_error(y_targetSVR, SVROutput))
print("Cross-Validation:")
crossValidatedScore = cross_val_score(SVRRegressor, x_inputSVR, y_inputSVR)
print(crossValidatedScore)

#Ignore this for now at least  vv
#Mean Square Error Rates
#print("Mean Square Error Rates:")
#MSEofRFROutput = mean_squared_error(

Task 1.1 | Data Preparation
RANDOM FOREST REGRESSOR:
Mean Absolute Error:
0.7709995312500003
Cross-Validation:
[0.97711457 0.97575185 0.98170593 0.97171752 0.97952932]
MLPREGRESSOR:
Mean Absolute Error:
0.7980640171363645
Cross-Validation:
[0.93300331 0.92406998 0.94039261 0.95136864 0.93094036]
SVR REGRESSOR:
Mean Absolute Error:
1.8411577276617672
Cross-Validation:
[0.91423908 0.91480769 0.90647643 0.91333156 0.93252901]
